# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rvrignon <rvrignon@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/28 15:05:07 by rvrignon          #+#    #+#              #
#    Updated: 2023/02/02 16:14:13 by rvrignon         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#include "iter.hpp"

int main() {
    
    int         numbers[]       = {10, 20, 30, 56, 85};
    std::string strings[]       = {"hjkdf", "dskj", "dsjkf"};
    char        characters[]    = {'d', 'e', 'f'};
    float       flotnb[]        = {42.0f, 1.2f, 985.894f};
…}